// uses {} as a placeholder

export const workMessages = [
  "You tutored a 12 year old and overcharged the parents. +{}, nice work.",
  "Why go to college when being a stripper paid you {}?",
  "Did someone order pizza? +{}",
  "Created a song and sold it! Somehow you made {}",
  "Your neighbor paid you {} for cutting their grass!",
  "Man, you only got {} for cleaning the sewers?",
  "You worked at Coaster Land and made {}",
  "You took up a shift at the local fast food place and earned {}",
  "You won a hot dog eating contest and the {} grand prize!",
  "You worked as on a weird discord bot that lets people touch grass, + {}",
  "You touched grass and got paid {}",
  "You took a shower! + {} (thank you)",
  "You had esex with a discord kitten. + {}",
  "You gave the creator of the bot lots of compliments. Thanks! + {}",
  "You drove an Uber for 12 hours. + {}",
  "Delivered food to people's homes. Now that's convenience! + {}",
  "Drew commissioned furry art for hours. + {}",
  "Ate someone's food while delivering with DoorDash™. + {}",
  "Served hot dogs at the national hot dog convention. + {}",
  "Made {} for dressing up in a maid outfit and cleaning someone's house",
  "Did some online therapy for others + {}",
  "Went on Beast Games™, netting you {} and also lifelong trauma.",
  "Became a backup dancer for Beyoncé for {}!",
  "Ate a hotdog, there was {} in it.",
  "Created Fake IDs for college students and earned {}",
  "Spoke at a Ted Talk about the effects of cat piss on chronic hair loss for {}",
  "Participated in the revolving door. + {}",
  "You tested mattresses in a furniture store you were not invited to. They paid you {} to leave.",
  "You helped me write these stupid work messages. + {}",
  "You help the nail salon by eating the nails of the ground. + {}",
  "You made and sold dolls of children's hair. + {}",
  "You created a hit trilogy based off a series of tragic murders, but before you create the third movie, you decided to kill a bunch of people, and your movie got shut down. + {}",
  "You made a crimonology report using BuzzFeed™ Unsolved™ as your source.",
  "You sold your grandmothers ashes. + {}",
  "You adopted a cat that has been abandoned by your neighbor for three years. + {}",
  "You ate a glue stick on a dare. + {}",
  "OnlyFans™ + {}",
  "You served on the jury for your friend accused of murder + {}",
];
